### ISSUE TITLE
Sulong for native interop?

### ISSUE THREAD

**Issue by kovasb** [thinktopic/cortex#13]
(posted similar message at https://github.com/uncomplicate/neanderthal/issues/21)

Sulong (https://github.com/graalvm/sulong) will run on unmodified JVM in Java 9. It is the basis for native extension interop for JRuby/Truffle. Full paper at http://ssw.jku.at/General/Staff/ManuelRigger/VMIL16.pdf

They make several claims regarding their FFI: 1) 0-overhead calls into native, 2) inlining of native calls. This is in addition to their primary claim of interpreting LLVM bitcode at seeds comparable to gcc o3.

I'm curious what people think for for use cases like Cortex. It seems like a path to get progressive optimization down to the fastest achievable speeds. 

The basic idea would be to develop a Truffle interpreter for Cortex primitives, starting with matrix computation but building up to the differentiable graph. The interpreter could specialize down into whatever combination of computation engines are available. Down to generating LLVM code (check out their impl of the LLVM AST, its pretty clean) and/or calling into native stuff.

**Comment by mikera** [comment]
It's a very interesting project! Keen to try this out when JDK9 become more available.

My view is that this level of optimisation is important when you are talking about operations on large arrays - so it is best use as a way to generate an optimised core.matrix implementation which we can then plug into cortex (for some or all of the matrices / vectors / tensors)

cortex should be a higher level library that can work with different underlying computation backends (this is essential if we want to be able to support a mix of JVM, GPU, Native, Javascript).

So my strategy would be:

 - Write the cortex code against the core.matrix API, so that backends can be switched
 - Have representations of networks that are backend-independent, so that networks can e.g. be trained on GPU and deployed on CLJS. This would ideally include tensorflow-like graphs of operations.
 - For stuff like differentials, expression manipulation I think this can be done at the generic graph API level
 - We can then experiment with sulong and other approaches to make fast backends as needed, while maintaining confidence that the higher level code won't need to be significantly changed.

**Comment by cnuernber** [comment]
I have a bit of a different strategy I would take.

This tech I think aligns well with things like the js compilation of blis:

https://github.com/Maratyszcza/blis-bench

I doubt we could get gemm any faster than parallel colt.  But there are lots of operations in the operation of a neural network that aren't expressable efficiently with gemm or with core.matrix.  Specifically convolutional layers and things like adam.

I could see a sizeable amount of c++ code in the implementation of cortex either compiled to llvm bytecode and then producing either asm.js, nacl, or this sort of intermediate representation.  Given we have that blis library it may be possible to build a gemm and a few other operations fast enough to equal parallel colt and we would extend the backend to ideally dynamically compile c++ kernels similar to how cuda or opencl work (on the cpu.  For javascript we would need to precompile everything or ask a server to compile it).

We then have an extensible efficient way to express operations that aren't able to be expressed well with core.matrix *and* we get very high execution speed of various things in the browser.  In addition when webassmbly starts gaining momentum we have a solid pathway to supporting it in whatever form it takes.

I was thinking it may furthermore be possible to unify a lot of the kernels depending on how they are expressed such that we have a common base of code for cuda, opencl, and sulong/llvm based compilation.

**Comment by cnuernber** [comment]
I have been considering and I decided that sulong is probably going the wrong directly in general.

If I am going to take the time to write c++ I expect to get a fairly significant benefit out of it.  Currently it provides two:
1.  Speed (sometimes).  This one is harder than it looks because hotspot really is fairly good with a lot of code.
2.  Synchronization primitives & memory model stuff.  This one is huge because compare-and-set allows parallelism and the c++11 memory model is like nothing that exists in java.  

Sulong cannot provide either of those; something that either dynamically compiled c++ like a cuda kernel or opencl running on the cpu would get me closer I think.  So after some consideration I just think the sulong project is misdirected.

**Comment by mikera** [comment]
Have you looked at what I have been experimenting with in vectorz-opencl? 

https://github.com/mikera/vectorz-opencl

It's GPU based at present, but I think it is a nice approach and it gives 100% interop with JVM Vectorz arrays and could easily be modified to use native code instead. I'm interested in making this work with cortex.

**Comment by cnuernber** [comment]
I hadn't seen it but it does look interesting.  I wish javacpp had a wrapper for opencl because then a lot of the code used for cuda could be reused for opecl.  

Without that, a new backend on the compute abstraction would be the quickest path to trying it out.

**Comment by cnuernber** [comment]
Closing this issue because we aren't going to go the sulong route any time soon.  A PR would definitely be accepted, however.
