### ISSUE TITLE
tests for serialization of parameters

### ISSUE THREAD

**Issue by shark8me** [thinktopic/cortex#74]
Hi,

I'd like to add tests for serialization of parameter values in a trained network (the code is in cortex/suite/src/cortex/suite/train.clj ). 
May I presume that a the right place to add it would be in cortex/suite/test/cortex/suite/train_test.clj? If someone else is working on adding tests for the same, I could help/collaborate. 

thanks!

**Comment by harold** [comment]
Hi @shark8me - thanks for these thoughts.

Did you encounter a problem with the parameter serialization?

We use the (ever-reliable) https://github.com/ptaoussanis/nippy clojure data serializer to persist the trained networks in suite.

I'd be interested to hear more about the improvements you'd like to see, or to see a PR. I don't know of anyone working on anything similar.

Let us know if you have further questions.

**Comment by shark8me** [comment]
Thanks @harold! 

I was looking for examples/tests that I could use, didn't find any, hence the question.
If I get an example/test working, I'll submit a PR.

**Comment by harold** [comment]
Sounds good! Thanks.

**Comment by mikera** [comment]
@harold is there any design doc re: serialisation?

I'm curious on our thinking on the relationship between:
- Serialisation of parameters only (then can be used to re-populate a network structure)
- Serialisation of logical networks (definition of operations but implementation independent)
- Serialisation of network with a specific implementation (maintaining backend types etc.)

**Comment by harold** [comment]
@mikera not that I know of.

Your first bullet point would be a slightly weird concept because the sizes of the parameter buffers depend on the relationships between the sizes of the layers in the network. Serializing the parameters without the network doesn't make much sense.

Your second point is generally called a 'description' throughout cortex. It's typically expressed as a vector of maps (e.g., https://github.com/thinktopic/cortex/blob/master/cortex/src/cortex/verify/nn/train.clj#L38) though more sophisticated network architectures are possibe.

Your third bullet point is not something cortex does currently. Instead we serialize the 'built' network (networks are built from descriptions to include parameters) in a backend-agnostic way. A built (and possibly trained) network can be saved a loaded from nippy as the suite training system does, and then executed on any backend.

Hope that helps.

**Comment by cnuernber** [comment]
@shark8me:  Any tests would be *greatly* appreciated.  Furthermore working in auto-generated tests (test.check) would also be greatly appreciated.

**Comment by cnuernber** [comment]
Writing a bit more about this because I was thinking about it last night.

Currently we serialize a fairly large datastructure that has two components I want to talk about.  First is the layer graph and this contains the network structure (edge list and nodes) along with a buffer list.  This is really the heart of cortex and we need to be careful to be minimal here as placing a lot of things in here carelessly will make upgrading the software much harder.

Second we also serialize the traversal system which is common among neural networks but it is also a lot less future proof.  

So there are two large sections of data that get serialized; one that should definitely be future proof and one which can be only partially future proof.  

If you play around in cortex' traversal tests I think you will get a feel for what gets saved (the entire network after the traversal->training or traversal->inference calls).  So far we usually store parameter buffers in vectorz-clj core.matrix bindings.  This does however present another issue in that if Mike updates vectorz-clj with a different binary structure that nippy picks up differently we could be in a tight spot.

So if someone wanted to be absolutely sure they would have a data format that could last a very long time and still be loadable probably you would want to just use persistent vectors in the buffers of the graph and the traversal instead of the vectorz-clj stuff.  

Just some thoughts.

**Comment by cnuernber** [comment]
@shark8me:  I think this bug is too general.  Do you see anything concrete to do about it at this time?

**Comment by shark8me** [comment]
I agree, it should be resolved, perhaps a specific bug could be added
instead.

On 16-Jun-2017 5:48 PM, "Chris Nuernberger" <notifications@github.com>
wrote:

@shark8me <https://github.com/shark8me>: I think this bug is too general.
Do you see anything concrete to do about it at this time?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/thinktopic/cortex/issues/74#issuecomment-309046206>,
or mute
the thread
